image: node:14

workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

pages:
  before_script:
    - RUN apk update && apk add bash
  script:
    - npm i
    - npm start
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
